name: Pedro Design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04301075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2ffff'
    - '#252324'
    - '#a2c5e5'
    - '#58606c'
    - '#a58d35'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
